services:
  eidash_api:
    image: ghcr.io/fyko/eidash-api:latest
    restart: unless-stopped
    networks:
      - default
      - caddy_network
    expose:
      - "33939"
    env_file:
      - .env.prod

  eidash_web:
    image: ghcr.io/fyko/eidash-web:latest
    networks:
      - default
      - caddy_network
    restart: unless-stopped
    expose:
      - "3000"
    env_file:
      - .env.prod

  redis:
    image: redis:alpine
    environment:
      REDIS_ARGS: --requirepass r2zjFhhb7O3CP7paDY6k2HpemAmEFdfouA8Fg4xii5i5ou9MjCr6fWB6vDVacAV0 --save 60 1 --loglevel warning
    restart: unless-stopped
    expose:
      - "6379"
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 3s
    volumes:
      - redis-storage:/data

  timescale:
    image: timescale/timescaledb-ha:pg16
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres # timscale doesnt let us change it
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?database password required}
      POSTGRES_DATABASE: ${POSTGRES_DATABASE:-eidash}
    volumes:
      - timescale-storage:/home/postgres/pgdata/data
      - ./docker/timescale/migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -d $${POSTGRES_DATABASE} -U $${POSTGRES_USER}",
        ]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 5s
    ports:
      - 5432:5432

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?database password required}
      POSTGRES_USER: eidash
      POSTGRES_DATABASE: ${POSTGRES_DATABASE:-eidash}
    volumes:
      - postgres-storage:/var/lib/postgresql/data
      - ./docker/postgres/postgresql.conf/:/etc/postgresql/postgresql.conf
    restart: unless-stopped
    expose:
      - "5432"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -d $${POSTGRES_DATABASE} -U $${POSTGRES_USER}",
        ]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 5s

volumes:
  postgres-storage:
  redis-storage:
  clickhouse-storage:
  clickhouse-logs:
  timescale-storage:

networks:
  default:
  caddy_network:
    external: true
