version: "3.9"

services:
  api:
    image: ghcr.io/fyko/eidash:latest
    restart: unless-stopped
    ports:
      - "39339:39339"
    env_file:
      - .env.prod

  web:
    image: ghcr.io/fyko/eidash-web:latest
    ports:
      - "3000:3000"
    restart: unless-stopped

  redis:
    image: redis:alpine
    command: --save 60 1 --loglevel warning
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 3s
    volumes:
      - redis-storage:/data
    ports:
      - "6379:6379"

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?database password required}
      POSTGRES_USER: ${POSTGRES_USER:-eidash}
      POSTGRES_DATABASE: ${POSTGRES_DATABASE:-eidash}
    volumes:
      - postgres-storage:/var/lib/postgresql/data
      - ./docker/postgres/postgresql.conf/:/etc/postgresql/postgresql.conf
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -d $${POSTGRES_DATABASE} -U $${POSTGRES_USER}",
        ]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 5s
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 1G

  clickhouse:
    image: clickhouse/clickhouse-server:24.3.2.23-alpine
    restart: always
    volumes:
      - clickhouse-storage:/var/lib/clickhouse
      - clickhouse-logs:/var/log/clickhouse-server
      - ./docker/clickhouse/clickhouse-config.xml:/etc/clickhouse-server/config.d/logging.xml:ro
      - ./docker/clickhouse/clickhouse-user-config.xml:/etc/clickhouse-server/users.d/logging.xml:ro
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8123/ping || exit 1
    ports:
      - 8123:8123
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    deploy:
      resources:
        limits:
          memory: 4G

volumes:
  postgres-storage:
  redis-storage:
  clickhouse-storage:
  clickhouse-logs:
