[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true

[config]
main_project_member = "eidash"
default_to_workspace = false

[tasks.setup]
script = '''
    echo installing git hooks
    pre-commit --version || pip install pre-commit
    pre-commit install || echo "failed to install git hooks!" 1>&2

    echo installing stuff for tests
    cargo binstall -y cargo-nextest
'''

[tasks.dev]
command = "cargo"
env_files = ["./.env"]
args = ["run"]
watch = { ignore_pattern = "eidash-web/*" }

[tasks.lint]
install_crate = "clippy"
command = "cargo"
args = ["clippy", "--tests", "--examples", "--all-targets", "--all-features"]

[tasks.fmt]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--all"]

[tasks.lint-ci]
install_crate = "clippy"
command = "cargo"
args = [
	"clippy",
	"--tests",
	"--examples",
	"--all-targets",
	"--all-features",
	"--workspace",
	"--",
	"-D",
	"warnings",
]

[tasks.fmt-ci]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--all", "--", "--check"]

# runs tests
[tasks.test]
env = { "RUN_MODE" = "test", "RUST_LOG" = "info", "RUST_BACKTRACE" = 0 }
command = "cargo"
args = [
	"nextest",
	"run",
	"--examples",
	"--all-targets",
	"--all-features",
	"${@}",
]

[tasks.test-ci]
env = { "RUN_MODE" = "ci", "RUST_LOG" = "info" }
command = "cargo"
args = ["nextest", "run", "--examples", "--all-targets", "--all-features"]
