name: CI

on:
  push:
    branches: [main]
    paths-ignore: ["**.md"]
  pull_request:
    paths-ignore: ["**.md"]

env:
  CARGO_TERM_COLOR: always
  CARGO_REGISTRIES_CRATES_IO_PROTOCOL: git
  PROTOC_VERSION: 3.23.4

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Add problem matchers
        uses: r7kamura/rust-problem-matchers@v1

      - name: Install Rust
        run: rustup toolchain install stable --profile minimal --no-self-update

      - name: Setup Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true

      - name: Install Cargo Make
        uses: davidB/rust-cargo-make@v1

      - name: Install protoc
        uses: taiki-e/install-action@v2
        with:
          tool: protoc@${{ env.PROTOC_VERSION }}

      - name: Format
        run: cargo make fmt-ci

      - name: Lint
        run: cargo make lint-ci

      - name: Build
        run: cargo build --all --release --all-features
